### ISSUE TITLE
dnf module install mariadb fails

### ISSUE THREAD

**Issue by alexxa** [modularity-modules/mariadb#6]
Error: 
Problem: conflicting requests
  - nothing provides bison needed by mariadb-server-3:10.2.8-2.module_6050b07a.x86_64

**Comment by alexxa** [comment]
@KarstenHopp

**Comment by KarstenHopp** [comment]
fixed in mbs-build #1105, mariadb-10.2-20171011143926

**Comment by alexxa** [comment]
why do I still see it in Modular-Bikeshed-20171023 ?  
mariadb - 20171019110412

Problem: conflicting requestsn  - nothing provides bison needed by mariadb-server-3:10.2.9-3.module_29db3494.x86_64

**Comment by alexxa** [comment]
@KarstenHopp the same issue is for mariadb/server

**Comment by KarstenHopp** [comment]
bikeshed is still using the master stream, I've fixed it in the 10.2 stream. There's a master build currently on its way with these changes: 
https://src.fedoraproject.org/modules/mariadb/c/d0a152537832b7bb4c4bdb068001b1f2bb92c160?branch=master

**Comment by alexxa** [comment]
@KarstenHopp I don't follow. I see error on 10.2 stream: 

sudo docker run bikeshed bash -l -c "dnf module install mariadb -y; dnf module list mariadb"

------------------------------- DNF ----------------------------------
Installed Packages
dnf.noarch          2.7.3-1.module_bf3f917d.modularity.5.4edc03e       @anaconda
libdnf.x86_64       0.11.1-1.module_c8380439                           @anaconda
----------------------------------------------------------------------
Image built with (KOJI composes):
		GIT:      	https://github.com/container-images/boltron-27
		Base:     	Fedora-Modular-27-20171115.n.1
Image running aginst (KOJI Composes):
		Base:     	Fedora-Modular-27-20171115.n.1
 ** NOTE: coreutils-single is installed, this will make things fail.
 **       you can fix it by: dnf --allowerasing install coreutils
 **       at which point @freeipa will install.
Fedora Modular Server 27 - x86_64 - Test Update  40 kB/s |  20 kB     00:00    
Fedora Modular Server 27 - x86_64 - Updates      71 kB/s |  20 kB     00:00    
Fedora Modular Server 27 - x86_64               7.8 MB/s | 4.5 MB     00:00    
Last metadata expiration check: 0:00:00 ago on Thu 16 Nov 2017 10:42:34 AM UTC.
Error: 
 Problem: conflicting requests
  - nothing provides bison needed by mariadb-server-3:10.2.9-3.module_15d35d06.x86_64

Name           Stream          Version               Profiles                   
mariadb        10.2 [d]        20171109104753        client, default, ...       

Hint: [d]efault, [e]nabled, [i]nstalled, [l]ocked
